### ISSUE TITLE
I can't built API_KEY 

### ISSUE THREAD

**Issue by akashjpro** [amanjeetsingh150/Televize#3]
Error when built "Error:(21, 0) Could not get unknown property 'API_KEY' for object of type com.android.build.gradle.AppExtension.
<a href="openFile:E:\More\Televize-master\app\build.gradle">Open File</a>"

Please help me, thanks

**Comment by amanjeetsingh150** [comment]
Hey @akashjpro You can paste your API key of MOVIE DB from this <a href="https://www.themoviedb.org/settings/api">API</a>  to your gradle.properties folder in your project which i have gitignore with name of API_KEY which will automatically take reference because of `buildTypes.each {
        it.buildConfigField('String', "TV_KEY", API_KEY)
}` in <a href="https://github.com/amanjeetsingh150/Televize/blob/master/app/build.gradle">build.gradle.</a>
Do tell me if there is any issue doing it. Thanks :+1:
